//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermercado.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SupermercadoEntities : DbContext
    {
        public SupermercadoEntities()
            : base("name=SupermercadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblProductos> TblProductos { get; set; }
    
        public virtual ObjectResult<SpListarProductos_Result> SpListarProductos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpListarProductos_Result>("SpListarProductos");
        }
    
        public virtual ObjectResult<SpListarProductoEditar_Result> SpListarProductoEditar(Nullable<int> prod_IdProducto)
        {
            var prod_IdProductoParameter = prod_IdProducto.HasValue ?
                new ObjectParameter("Prod_IdProducto", prod_IdProducto) :
                new ObjectParameter("Prod_IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpListarProductoEditar_Result>("SpListarProductoEditar", prod_IdProductoParameter);
        }
    
        public virtual int SpEditarProductos(Nullable<int> prod_IdProducto, string prod_NombreProducto, Nullable<decimal> prod_Precio, Nullable<int> prod_Existencias)
        {
            var prod_IdProductoParameter = prod_IdProducto.HasValue ?
                new ObjectParameter("Prod_IdProducto", prod_IdProducto) :
                new ObjectParameter("Prod_IdProducto", typeof(int));
    
            var prod_NombreProductoParameter = prod_NombreProducto != null ?
                new ObjectParameter("Prod_NombreProducto", prod_NombreProducto) :
                new ObjectParameter("Prod_NombreProducto", typeof(string));
    
            var prod_PrecioParameter = prod_Precio.HasValue ?
                new ObjectParameter("Prod_Precio", prod_Precio) :
                new ObjectParameter("Prod_Precio", typeof(decimal));
    
            var prod_ExistenciasParameter = prod_Existencias.HasValue ?
                new ObjectParameter("Prod_Existencias", prod_Existencias) :
                new ObjectParameter("Prod_Existencias", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpEditarProductos", prod_IdProductoParameter, prod_NombreProductoParameter, prod_PrecioParameter, prod_ExistenciasParameter);
        }
    
        public virtual int SpEliminarProductos(Nullable<int> prod_IdProducto)
        {
            var prod_IdProductoParameter = prod_IdProducto.HasValue ?
                new ObjectParameter("Prod_IdProducto", prod_IdProducto) :
                new ObjectParameter("Prod_IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SpEliminarProductos", prod_IdProductoParameter);
        }
    
        public virtual ObjectResult<SpCrearProductos_Result> SpCrearProductos(string prod_NombreProducto, Nullable<decimal> prod_Precio, Nullable<int> prod_Existencias)
        {
            var prod_NombreProductoParameter = prod_NombreProducto != null ?
                new ObjectParameter("Prod_NombreProducto", prod_NombreProducto) :
                new ObjectParameter("Prod_NombreProducto", typeof(string));
    
            var prod_PrecioParameter = prod_Precio.HasValue ?
                new ObjectParameter("Prod_Precio", prod_Precio) :
                new ObjectParameter("Prod_Precio", typeof(decimal));
    
            var prod_ExistenciasParameter = prod_Existencias.HasValue ?
                new ObjectParameter("Prod_Existencias", prod_Existencias) :
                new ObjectParameter("Prod_Existencias", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SpCrearProductos_Result>("SpCrearProductos", prod_NombreProductoParameter, prod_PrecioParameter, prod_ExistenciasParameter);
        }
    }
}
